// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: base

#include "../ui.h"

void ui_comp_Slider2_create_hook(lv_obj_t * comp)
{
}
