// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: base

#include "ui.h"
#include "esp_log.h"

#include "hal_display_logic.h"
#include "shared_resources.h"

static const char *TAG = "ui_events.c: ";

extern QueueHandle_t main_queue_event;

// void connect_to_server(lv_event_t * e)
// {
// 	ESP_LOGD(TAG, "Button has been CLICKED");
// 	app_event_t ev;
// 	ev.source = EVENT_SOURCE_GUI;
// 	ev.CmdCode = GUI_EVENT_CONNECT_TO_SERVER;
// 	xQueueSend(main_queue_event, &ev, 0);
// }

// void event_roller_selection_changed(lv_event_t * e)
// {
// 	lv_obj_t * roller = lv_event_get_target(e);
//     uint16_t selected_index = lv_roller_get_selected(roller);

//     peer_info_t peer_data = hal_display_get_peer_by_index(selected_index);

// 	ESP_LOGD(TAG, "GUI_ROLLER_CHANGED");
// 	app_event_t event = {
//         .source = EVENT_SOURCE_GUI,
//         .CmdCode = GUI_EVENT_PEER_SELECTED, // Додайте цей тип в app_events.h
//         .payload.gui.selected_peer = selected_index, // Передаємо індекс вибраного елемента
//         .payload.gui.peer_info = peer_data,
//     };
// 	xQueueSend(main_queue_event, &event, 0);
// }
