// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: base

#include "../ui.h"

lv_obj_t * uic_panel_tx_overlay;
lv_obj_t * uic_label_info_mem_value;
lv_obj_t * uic_label_info_mem_title;
lv_obj_t * uic_label_info_name_value;
lv_obj_t * uic_label_info_name_title;
lv_obj_t * uic_label_info_sn_value;
lv_obj_t * uic_label_info_sn_title;
lv_obj_t * uic_label_info_ip_value;
lv_obj_t * uic_label_info_ip_title;
lv_obj_t * uic_slider_volume;
lv_obj_t * uic_label_volume_title;
lv_obj_t * uic_roller_peer_list;
lv_obj_t * uic_tab_peers;
lv_obj_t * uic_tabview_main;
lv_obj_t * uic_img_tx_status;
lv_obj_t * uic_img_rx_status;
lv_obj_t * uic_img_wifi_status;
lv_obj_t * uic_label_battery_percent;
lv_obj_t * uic_bar_battery_status;
lv_obj_t * uic_label_clock;
lv_obj_t * uic_panel_header;
lv_obj_t * uic_screen_main;
lv_obj_t * ui_screenmain_ = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_labelclock = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_labelbatterypercent = NULL;
lv_obj_t * ui_imgwifistatus = NULL;
lv_obj_t * ui_imgrxstatus = NULL;
lv_obj_t * ui_imgtxstatus = NULL;
lv_obj_t * ui_tabviewmain = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_rollerpeerlist = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_labelvolumetitle = NULL;
lv_obj_t * ui_slidervolume = NULL;
lv_obj_t * ui_TabPage3 = NULL;
lv_obj_t * ui_labelinfoiptitle_ = NULL;
lv_obj_t * ui_labelinfoipvalue = NULL;
lv_obj_t * ui_labelinfosntitle_ = NULL;
lv_obj_t * ui_labelinfosnvalue_ = NULL;
lv_obj_t * ui_labelinfonametitle_ = NULL;
lv_obj_t * ui_labelinfonamevalue_ = NULL;
lv_obj_t * ui_labelinfomemtitle_ = NULL;
lv_obj_t * ui_labelinfomemvalue_ = NULL;
lv_obj_t * ui_paneltxoverlay = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_slidervolume(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_labelvolumetitle, target, "Volume: ", "");
    }
}

// build funtions

void ui_screenmain__screen_init(void)
{
    ui_screenmain_ = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screenmain_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_screenmain_);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 240);
    lv_obj_set_height(ui_Container1, 35);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelclock = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelclock, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_labelclock, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_labelclock, 5);
    lv_obj_set_y(ui_labelclock, 3);
    lv_label_set_text(ui_labelclock, "00:00");
    lv_obj_set_style_text_font(ui_labelclock, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Container1);
    lv_bar_set_value(ui_Bar1, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 50);
    lv_obj_set_height(ui_Bar1, 25);
    lv_obj_set_x(ui_Bar1, -5);
    lv_obj_set_y(ui_Bar1, 5);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_border_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFF7900), LV_PART_INDICATOR | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_USER_3);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar1,
                                                                                           lv_obj_get_style_pad_right(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_labelbatterypercent = lv_label_create(ui_Bar1);
    lv_obj_set_width(ui_labelbatterypercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelbatterypercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelbatterypercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelbatterypercent, "70 %");
    lv_obj_set_style_text_color(ui_labelbatterypercent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelbatterypercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgwifistatus = lv_image_create(ui_Container1);
    lv_image_set_src(ui_imgwifistatus, &ui_img_wifi_png);
    lv_obj_set_width(ui_imgwifistatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgwifistatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgwifistatus, -60);
    lv_obj_set_y(ui_imgwifistatus, 0);
    lv_obj_set_align(ui_imgwifistatus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_imgwifistatus, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_imgwifistatus,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_imgrxstatus = lv_image_create(ui_Container1);
    lv_image_set_src(ui_imgrxstatus, &ui_img_rx_png);
    lv_obj_set_width(ui_imgrxstatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgrxstatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgrxstatus, -95);
    lv_obj_set_y(ui_imgrxstatus, 0);
    lv_obj_set_align(ui_imgrxstatus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_imgrxstatus, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_imgrxstatus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_imgtxstatus = lv_image_create(ui_Container1);
    lv_image_set_src(ui_imgtxstatus, &ui_img_tx_png);
    lv_obj_set_width(ui_imgtxstatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgtxstatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgtxstatus, -95);
    lv_obj_set_y(ui_imgtxstatus, 0);
    lv_obj_set_align(ui_imgtxstatus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_imgtxstatus, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_imgtxstatus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_tabviewmain = lv_tabview_create(ui_screenmain_);
    lv_tabview_set_tab_bar_position(ui_tabviewmain, LV_DIR_RIGHT);
    lv_tabview_set_tab_bar_size(ui_tabviewmain, 60);
    lv_obj_set_width(ui_tabviewmain, 240);
    lv_obj_set_height(ui_tabviewmain, 205);
    lv_obj_set_x(ui_tabviewmain, 0);
    lv_obj_set_y(ui_tabviewmain, 35);
    lv_obj_remove_flag(ui_tabviewmain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage1 = lv_tabview_add_tab(ui_tabviewmain, "Peers");

    ui_rollerpeerlist = lv_roller_create(ui_TabPage1);
    lv_roller_set_options(ui_rollerpeerlist, "ALL\nUser 1\nUser 2", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_rollerpeerlist, 150);
    lv_obj_set_height(ui_rollerpeerlist, 175);
    lv_obj_add_state(ui_rollerpeerlist, LV_STATE_EDITED);       /// States
    lv_obj_set_style_text_font(ui_rollerpeerlist, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_decor(ui_rollerpeerlist, LV_TEXT_DECOR_UNDERLINE, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerpeerlist, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_TabPage2 = lv_tabview_add_tab(ui_tabviewmain, "SET");

    ui_labelvolumetitle = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_labelvolumetitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelvolumetitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelvolumetitle, 7);
    lv_obj_set_y(ui_labelvolumetitle, -91);
    lv_obj_set_align(ui_labelvolumetitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_labelvolumetitle, "Volume:");

    ui_slidervolume = lv_slider_create(ui_TabPage2);
    lv_slider_set_range(ui_slidervolume, 10, 100);
    lv_slider_set_value(ui_slidervolume, 75, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slidervolume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_slidervolume, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_slidervolume, 144);
    lv_obj_set_height(ui_slidervolume, 19);
    lv_obj_set_x(ui_slidervolume, -2);
    lv_obj_set_y(ui_slidervolume, -62);
    lv_obj_set_align(ui_slidervolume, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_slidervolume, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_slidervolume,
                                                                                                   lv_obj_get_style_pad_right(ui_slidervolume, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_TabPage3 = lv_tabview_add_tab(ui_tabviewmain, "Info");

    ui_labelinfoiptitle_ = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_labelinfoiptitle_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelinfoiptitle_, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_labelinfoiptitle_, "IP Address:");

    ui_labelinfoipvalue = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_labelinfoipvalue, LV_SIZE_CONTENT);   /// 78
    lv_obj_set_height(ui_labelinfoipvalue, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_labelinfoipvalue, 35);
    lv_obj_set_y(ui_labelinfoipvalue, 25);
    lv_label_set_long_mode(ui_labelinfoipvalue, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_labelinfoipvalue, "192.168.0.1");

    ui_labelinfosntitle_ = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_labelinfosntitle_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelinfosntitle_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelinfosntitle_, -1);
    lv_obj_set_y(ui_labelinfosntitle_, 50);
    lv_label_set_text(ui_labelinfosntitle_, "Serial D:");

    ui_labelinfosnvalue_ = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_labelinfosnvalue_, LV_SIZE_CONTENT);   /// 87
    lv_obj_set_height(ui_labelinfosnvalue_, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_labelinfosnvalue_, 35);
    lv_obj_set_y(ui_labelinfosnvalue_, 75);
    lv_label_set_long_mode(ui_labelinfosnvalue_, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_labelinfosnvalue_, "AABBCCDDEEFF");

    ui_labelinfonametitle_ = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_labelinfonametitle_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelinfonametitle_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelinfonametitle_, 0);
    lv_obj_set_y(ui_labelinfonametitle_, 100);
    lv_label_set_text(ui_labelinfonametitle_, "Device Name:");

    ui_labelinfonamevalue_ = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_labelinfonamevalue_, LV_SIZE_CONTENT);   /// 57
    lv_obj_set_height(ui_labelinfonamevalue_, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_labelinfonamevalue_, 35);
    lv_obj_set_y(ui_labelinfonamevalue_, 125);
    lv_label_set_long_mode(ui_labelinfonamevalue_, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_labelinfonamevalue_, "MyRadio");

    ui_labelinfomemtitle_ = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_labelinfomemtitle_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelinfomemtitle_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelinfomemtitle_, 0);
    lv_obj_set_y(ui_labelinfomemtitle_, 150);
    lv_label_set_text(ui_labelinfomemtitle_, "Free RAM:");

    ui_labelinfomemvalue_ = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_labelinfomemvalue_, LV_SIZE_CONTENT);   /// 65
    lv_obj_set_height(ui_labelinfomemvalue_, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_labelinfomemvalue_, 35);
    lv_obj_set_y(ui_labelinfomemvalue_, 175);
    lv_label_set_long_mode(ui_labelinfomemvalue_, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_labelinfomemvalue_, "123 KB");

    ui_paneltxoverlay = lv_obj_create(ui_screenmain_);
    lv_obj_set_width(ui_paneltxoverlay, 240);
    lv_obj_set_height(ui_paneltxoverlay, 240);
    lv_obj_set_align(ui_paneltxoverlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_paneltxoverlay, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_paneltxoverlay,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_paneltxoverlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_paneltxoverlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_paneltxoverlay, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_paneltxoverlay, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_paneltxoverlay);
    lv_image_set_src(ui_Image1, &ui_img_trans_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Image1, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_slidervolume, ui_event_slidervolume, LV_EVENT_ALL, NULL);
    uic_screen_main = ui_screenmain_;
    uic_panel_header = ui_Container1;
    uic_label_clock = ui_labelclock;
    uic_bar_battery_status = ui_Bar1;
    uic_label_battery_percent = ui_labelbatterypercent;
    uic_img_wifi_status = ui_imgwifistatus;
    uic_img_rx_status = ui_imgrxstatus;
    uic_img_tx_status = ui_imgtxstatus;
    uic_tabview_main = ui_tabviewmain;
    uic_tab_peers = ui_TabPage1;
    uic_roller_peer_list = ui_rollerpeerlist;
    uic_label_volume_title = ui_labelvolumetitle;
    uic_slider_volume = ui_slidervolume;
    uic_label_info_ip_title = ui_labelinfoiptitle_;
    uic_label_info_ip_value = ui_labelinfoipvalue;
    uic_label_info_sn_title = ui_labelinfosntitle_;
    uic_label_info_sn_value = ui_labelinfosnvalue_;
    uic_label_info_name_title = ui_labelinfonametitle_;
    uic_label_info_name_value = ui_labelinfonamevalue_;
    uic_label_info_mem_title = ui_labelinfomemtitle_;
    uic_label_info_mem_value = ui_labelinfomemvalue_;
    uic_panel_tx_overlay = ui_paneltxoverlay;

}

void ui_screenmain__screen_destroy(void)
{
    if(ui_screenmain_) lv_obj_del(ui_screenmain_);

    // NULL screen variables
    uic_screen_main = NULL;
    ui_screenmain_ = NULL;
    uic_panel_header = NULL;
    ui_Container1 = NULL;
    uic_label_clock = NULL;
    ui_labelclock = NULL;
    uic_bar_battery_status = NULL;
    ui_Bar1 = NULL;
    uic_label_battery_percent = NULL;
    ui_labelbatterypercent = NULL;
    uic_img_wifi_status = NULL;
    ui_imgwifistatus = NULL;
    uic_img_rx_status = NULL;
    ui_imgrxstatus = NULL;
    uic_img_tx_status = NULL;
    ui_imgtxstatus = NULL;
    uic_tabview_main = NULL;
    ui_tabviewmain = NULL;
    uic_tab_peers = NULL;
    ui_TabPage1 = NULL;
    uic_roller_peer_list = NULL;
    ui_rollerpeerlist = NULL;
    ui_TabPage2 = NULL;
    uic_label_volume_title = NULL;
    ui_labelvolumetitle = NULL;
    uic_slider_volume = NULL;
    ui_slidervolume = NULL;
    ui_TabPage3 = NULL;
    uic_label_info_ip_title = NULL;
    ui_labelinfoiptitle_ = NULL;
    uic_label_info_ip_value = NULL;
    ui_labelinfoipvalue = NULL;
    uic_label_info_sn_title = NULL;
    ui_labelinfosntitle_ = NULL;
    uic_label_info_sn_value = NULL;
    ui_labelinfosnvalue_ = NULL;
    uic_label_info_name_title = NULL;
    ui_labelinfonametitle_ = NULL;
    uic_label_info_name_value = NULL;
    ui_labelinfonamevalue_ = NULL;
    uic_label_info_mem_title = NULL;
    ui_labelinfomemtitle_ = NULL;
    uic_label_info_mem_value = NULL;
    ui_labelinfomemvalue_ = NULL;
    uic_panel_tx_overlay = NULL;
    ui_paneltxoverlay = NULL;
    ui_Image1 = NULL;

}
