// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: base

#ifndef UI_SCREENMAIN__H
#define UI_SCREENMAIN__H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenmain_
extern void ui_screenmain__screen_init(void);
extern void ui_screenmain__screen_destroy(void);
extern lv_obj_t * ui_screenmain_;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_labelclock;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_labelbatterypercent;
extern lv_obj_t * ui_imgwifistatus;
extern lv_obj_t * ui_imgrxstatus;
extern lv_obj_t * ui_imgtxstatus;
extern lv_obj_t * ui_tabviewmain;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_rollerpeerlist;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_labelvolumetitle;
extern void ui_event_slidervolume(lv_event_t * e);
extern lv_obj_t * ui_slidervolume;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_labelinfoiptitle_;
extern lv_obj_t * ui_labelinfoipvalue;
extern lv_obj_t * ui_labelinfosntitle_;
extern lv_obj_t * ui_labelinfosnvalue_;
extern lv_obj_t * ui_labelinfonametitle_;
extern lv_obj_t * ui_labelinfonamevalue_;
extern lv_obj_t * ui_labelinfomemtitle_;
extern lv_obj_t * ui_labelinfomemvalue_;
extern lv_obj_t * ui_paneltxoverlay;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_screen_main;
extern lv_obj_t * uic_panel_header;
extern lv_obj_t * uic_label_clock;
extern lv_obj_t * uic_bar_battery_status;
extern lv_obj_t * uic_label_battery_percent;
extern lv_obj_t * uic_img_wifi_status;
extern lv_obj_t * uic_img_rx_status;
extern lv_obj_t * uic_img_tx_status;
extern lv_obj_t * uic_tabview_main;
extern lv_obj_t * uic_tab_peers;
extern lv_obj_t * uic_roller_peer_list;
extern lv_obj_t * uic_label_volume_title;
extern lv_obj_t * uic_slider_volume;
extern lv_obj_t * uic_label_info_ip_title;
extern lv_obj_t * uic_label_info_ip_value;
extern lv_obj_t * uic_label_info_sn_title;
extern lv_obj_t * uic_label_info_sn_value;
extern lv_obj_t * uic_label_info_name_title;
extern lv_obj_t * uic_label_info_name_value;
extern lv_obj_t * uic_label_info_mem_title;
extern lv_obj_t * uic_label_info_mem_value;
extern lv_obj_t * uic_panel_tx_overlay;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

